sudo: requiered
language: generic 

services:
    - docker

before_install:
#    - docker build -t f1paco/docker-react -f Dockerfile.dev .
    - docker build -t f1paco/docker-react -f Dockerfile.dev .

script:
#    - docker run USERNAME/docker-react npm run test -- --coverage
    - docker run -e CI=true f1paco/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-369212418352"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
