sudo: requiered
language: generic 

services:
    - docker

before_install:
    - docker build -t f1paco/docker-react -f Dockerfile.dev .

script:
#    - docker run USERNAME/docker-react npm run test -- --coverage
    - docker run -e CI=true f1paco/docker-react npm run test